name:                spock-blog
version:             0.1.0.0
github:              "DanielBlanco/spock-blog"
license:             MIT
author:              "Daniel Blanco"
maintainer:          "daniel.blancorojas@gmail.com"
copyright:           "2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DanielBlanco/spock-blog#readme>

dependencies:
- base >= 4.7 && < 5
- Spock >=0.11
- mtl
- text

library:
  source-dirs: src

executables:
  spock-blog-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spock-blog

tests:
  spock-blog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spock-blog
